# 34scoring matrix by Ethan Djou


print(end='   ')
print('A', end='  ')
print('C', end='  ')
print('G', end='  ')
print('T')
print('A', end=' ')
print('+1', end=' ')
print('-1', end=' ')
print('-1', end=' ')
print('-1')
print('C', end=' ')
print('-1', end=' ')
print('+1', end=' ')
print('-1', end=' ')
print('-1')
print('G', end=' ')
print('-1', end=' ')
print('-1', end=' ')
print('+1', end=' ')
print('-1')
print('T', end=' ')
print('-1', end=' ')
print('-1', end=' ')
print('-1', end=' ')
print('+1')